check all options of timidity

diff --git a/tools/timidity/pianobooster-timidity b/tools/timidity/pianobooster-timidity
--- a/tools/timidity/pianobooster-timidity
+++ b/tools/timidity/pianobooster-timidity
@@ -10,15 +10,32 @@ timidity=`timidity -v 2>/dev/null`
 
 if [ -z "$timidity" ]
 then
+  timidity=`timidity -h 2>/dev/null`
+fi
+
+if [ -z "$timidity" ]
+then
    echo "Error: timidity was not found or broken!"
    exit 1
 fi
 
-if [ ! -z "`timidity -help|grep '\-OO'`" ]
+if [ ! -z "`timidity -help|grep '\-iA'`" ]
 then
-  timidity -iA -OO &
+  if [ ! -z "`timidity -help|grep '\-OO'`" ]
+  then
+    timidity -iA -OO &
+  else
+    if [ ! -z "`timidity -help|grep '\-Os'`" ]
+    then
+      timidity -iA -Os &
+    else
+      echo "Error: timidity does not have -OO or -Os options!"
+      exit 1
+    fi
+  fi
 else
-  timidity -iA -Os &
+  echo "Error: timidity does not have -iA option!"
+  exit 1
 fi
 
 PID=$!
