tools: timidity: check if timidity is installed

diff --git a/tools/timidity/pianobooster-timidity b/tools/timidity/pianobooster-timidity
--- a/tools/timidity/pianobooster-timidity
+++ b/tools/timidity/pianobooster-timidity
@@ -1,4 +1,10 @@
 #!/bin/sh
+timidity=`timidity -v 2>/dev/null`
+if [ -z "$timidity" ]
+then
+   echo "Error: timidity was not found or broken!"
+   exit 1
+fi
 timidity -iA -OO &
 PID=$!
 pianobooster
